# Generated by Django 3.1.2 on 2020-10-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='traineRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('branch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='zone', chained_model_field='zone', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.designation')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='zone', chained_model_field='zone', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.zone')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.zone'),
        ),
    ]
