# Generated by Django 3.1.2 on 2020-10-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='trainerequest',
            options={'ordering': ['designation'], 'verbose_name_plural': 'Training Requests'},
        ),
        migrations.AlterModelOptions(
            name='training_title',
            options={'verbose_name_plural': 'Training Title'},
        ),
        migrations.RemoveField(
            model_name='trainerequest',
            name='email',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trainerequest',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='training_title',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
