# Generated by Django 3.1.2 on 2020-10-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineRequestAdmin',
            fields=[
                ('trainerequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.trainerequest')),
            ],
            bases=('accounts.trainerequest',),
        ),
    ]
