# Generated by Django 3.1.2 on 2020-10-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_trainerequestadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Training_Title',
        ),
        migrations.AlterModelOptions(
            name='trainerequest',
            options={'ordering': ['designation']},
        ),
        migrations.AddField(
            model_name='profile',
            name='ChangePass',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TraineRequestAdmin',
        ),
    ]
